// Pixel art drawn as character grids. Each char maps to a palette color,
// '.' is transparent. Rendered as crisp SVG by <app-pixel>.

export const palette: Record<string, string> = {
  k: '#0b0b0b', // outline
  w: '#f0f0f0', // white
  g: '#9a9a9a', // grey
  d: '#4a4a4a', // dark grey
  r: '#e53935', // brand red
  R: '#8e1b18', // dark red
  p: '#ff8a80', // pink
  y: '#ffd54f', // yellow
  b: '#6d4c41', // brown
};

export type SpriteName = keyof typeof sprites;

export const sprites = {
  cat: [
    '..kk........kk..',
    '.kgrk......krgk.',
    '.kgggk....kgggk.',
    '.kggggkkkkggggk.',
    'kggggggggggggggk',
    'kgggkkggggkkgggk',
    'kgggkrggggkrgggk',
    'kggggggppggggggk',
    '.kggggkkkkggggk.',
    '..kkggggggggkk..',
    '..kggwwwwwwggk..',
    '.kggwwwwwwwwggk.',
    '.kggwwwwwwwwggkk',
    '.kgggwwwwwwgggkg',
    '.kggkgggggkggkgk',
    '..kkkkkkkkkkkkk.',
  ],
  catBlink: [
    '..kk........kk..',
    '.kgrk......krgk.',
    '.kgggk....kgggk.',
    '.kggggkkkkggggk.',
    'kggggggggggggggk',
    'kggggggggggggggk',
    'kgggkkggggkkgggk',
    'kggggggppggggggk',
    '.kggggkkkkggggk.',
    '..kkggggggggkk..',
    '..kggwwwwwwggk..',
    '.kggwwwwwwwwggk.',
    '.kggwwwwwwwwggkk',
    '.kgggwwwwwwgggkg',
    '.kggkgggggkggkgk',
    '..kkkkkkkkkkkkk.',
  ],
  home: [
    '.....kk.....',
    '....krrk....',
    '...krrrrk...',
    '..krrrrrrk..',
    '.krrrrrrrrk.',
    'kkkkkkkkkkkk',
    '.kwwwwwwwwk.',
    '.kwkkwwbbwk.',
    '.kwkkwwbbwk.',
    '.kwwwwwbbwk.',
    '.kkkkkkkkkk.',
  ],
  briefcase: [
    '....kkkk....',
    '...k....k...',
    'kkkkkkkkkkkk',
    'kbbbbbbbbbbk',
    'kbbbbbbbbbbk',
    'kkkkkyykkkkk',
    'kbbbbyybbbbk',
    'kbbbbbbbbbbk',
    'kbbbbbbbbbbk',
    'kkkkkkkkkkkk',
  ],
  folder: [
    'kkkkk.......',
    'kyyyyk......',
    'kyyyyykkkkkk',
    'kyyyyyyyyyyk',
    'kkkkkkkkkkkk',
    'kyyyyyyyyyyk',
    'kyyyyyyyyyyk',
    'kyyyyyyyyyyk',
    'kyyyyyyyyyyk',
    'kkkkkkkkkkkk',
  ],
  star: [
    '.....kk.....',
    '....kyyk....',
    '....kyyk....',
    'kkkkyyyykkkk',
    'kyyyyyyyyyyk',
    '.kyyyyyyyyk.',
    '..kyyyyyyk..',
    '..kyyyyyyk..',
    '.kyyykkyyyk.',
    '.kyyk..kyyk.',
    'kkk......kkk',
  ],
  chain: [
    '......kkkk..',
    '.....kggggk.',
    '....kgk..kgk',
    '....kgk..kgk',
    '..kkkgkk.kgk',
    '.kggggggkgk.',
    'kgk.kgk.kk..',
    'kgk..kk.....',
    'kgk..kgk....',
    '.kggggk.....',
    '..kkkk......',
  ],
  mail: [
    'kkkkkkkkkkkk',
    'kkwwwwwwwwkk',
    'kwkwwwwwwkwk',
    'kwwkwwwwkwwk',
    'kwwwkrrkwwwk',
    'kwwkwkkwkwwk',
    'kwkwwwwwwkwk',
    'kkwwwwwwwwkk',
    'kkkkkkkkkkkk',
  ],
  heart: [
    '.kk...kk.',
    'krrk.krrk',
    'krwrkrrrk',
    'krrrrrrrk',
    '.krrrrrk.',
    '..krrrk..',
    '...krk...',
    '....k....',
  ],
  note: [
    '...wwwwww',
    '...wwwwww',
    '...w....w',
    '...w....w',
    '...w....w',
    '.rrw..rrw',
    'rrrw.rrrw',
    'rrrr.rrrr',
    '.rr...rr.',
  ],
  floppy: [
    'kkkkkkkkkkk.',
    'krkwwwwwkrkk',
    'krkwwwwwkrrk',
    'krkwwwwwkrrk',
    'krkkkkkkkrrk',
    'krrrrrrrrrrk',
    'krkkkkkkkkrk',
    'krkwwwwwwkrk',
    'krkwwwwwwkrk',
    'kkkkkkkkkkkk',
  ],
  coffee: [
    '..g..g....',
    '...g..g...',
    '..g..g....',
    'kkkkkkkk..',
    'kwwwwwwkkk',
    'kwbbbbwk.k',
    'kwwwwwwk.k',
    'kwwwwwwkkk',
    '.kwwwwk...',
    '..kkkk....',
  ],
} satisfies Record<string, string[]>;
